/* Generated by scripts/tableslop/hunter-prep.js --export (2026-08-06T03:49:28.226Z).
 * Do not hand-edit; regenerate. Deterministic: same cases -> same orders/rolls. */
window.HUNTER_DATA = {
  "meta": {
    "generator": "scripts/tableslop/hunter-prep.js --export",
    "generated_at": "2026-08-06T03:49:28.226Z",
    "campaign": "tropic-gooner",
    "silo": "hunter-reckoning",
    "case_count": 15,
    "doc": "campaigns/tropic-gooner/worldbuilding/HUNTER.md",
    "note": "Deterministic bundle. All rolls/orders precomputed by the CLI; the board UI only renders and walks them."
  },
  "veil": {
    "actions": [
      "research",
      "interview",
      "surveillance",
      "scene"
    ],
    "tiers": [
      {
        "tier": 0,
        "at": 0,
        "label": "mundane cover"
      },
      {
        "tier": 1,
        "at": 2,
        "label": "seam visible"
      },
      {
        "tier": 2,
        "at": 5,
        "label": "pattern named"
      },
      {
        "tier": 3,
        "at": 8,
        "label": "fully exposed"
      }
    ],
    "unlocks": {
      "profile_at_tier": 2,
      "weaknesses_at_tier": 3
    }
  },
  "gear": [
    {
      "id": "rock_salt",
      "name": "Rock salt, 25 lb",
      "source": "hardware store / grocery",
      "price": 15,
      "legality": "legal",
      "tags": [
        "salt"
      ]
    },
    {
      "id": "cold_iron",
      "name": "Cold iron bar (dock-salvage fire iron)",
      "source": "blacksmith / dock salvage",
      "price": 120,
      "legality": "gray (salvage paperwork)",
      "tags": [
        "cold_iron"
      ]
    },
    {
      "id": "silver",
      "name": "Silver load / silvered blade",
      "source": "black market",
      "price": 400,
      "legality": "gray (legal to own, suspicious to buy)",
      "tags": [
        "silver"
      ]
    },
    {
      "id": "uv_rig",
      "name": "UV rig (reptile lamps, handheld array)",
      "source": "pet / hardware store",
      "price": 90,
      "legality": "legal",
      "tags": [
        "uv"
      ]
    },
    {
      "id": "stakes",
      "name": "Hardwood stakes, fire-hardened",
      "source": "hardware lumber",
      "price": 10,
      "legality": "legal",
      "tags": [
        "stake"
      ]
    },
    {
      "id": "blessed_kit",
      "name": "Blessed kit (holy water, chalk, cord, cutters)",
      "source": "church donation",
      "price": 40,
      "legality": "legal",
      "tags": [
        "blessed"
      ]
    },
    {
      "id": "flares",
      "name": "Road flares / accelerant",
      "source": "hardware / gas station",
      "price": 25,
      "legality": "illegal-use",
      "tags": [
        "fire"
      ]
    },
    {
      "id": "bee_smoker",
      "name": "Bee smoker",
      "source": "farm supply",
      "price": 35,
      "legality": "legal",
      "tags": [
        "smoke"
      ]
    },
    {
      "id": "machete",
      "name": "Machete",
      "source": "farm supply",
      "price": 30,
      "legality": "legal-ish",
      "tags": [
        "melee"
      ]
    },
    {
      "id": "shotgun",
      "name": "Shotgun, county permit",
      "source": "sporting goods",
      "price": 350,
      "legality": "legal-with-permit, heat-heavy",
      "tags": [
        "firearm"
      ]
    },
    {
      "id": "vest",
      "name": "Surplus vest",
      "source": "black market",
      "price": 300,
      "legality": "gray",
      "tags": [
        "armor"
      ]
    },
    {
      "id": "seawater",
      "name": "Running seawater (the bay)",
      "source": "the bay",
      "price": 0,
      "legality": "legal",
      "tags": [
        "seawater"
      ]
    }
  ],
  "outcome_tables": {
    "prepared": {
      "1": {
        "clean_win": 0.9,
        "win_with_cost": 0.08,
        "disaster": 0.02
      },
      "2": {
        "clean_win": 0.77,
        "win_with_cost": 0.17,
        "disaster": 0.06
      },
      "3": {
        "clean_win": 0.64,
        "win_with_cost": 0.26,
        "disaster": 0.1
      },
      "4": {
        "clean_win": 0.51,
        "win_with_cost": 0.35,
        "disaster": 0.14
      },
      "5": {
        "clean_win": 0.38,
        "win_with_cost": 0.44,
        "disaster": 0.18
      }
    },
    "rushed": {
      "1": {
        "clean_win": 0.3,
        "win_with_cost": 0.48,
        "disaster": 0.22
      },
      "2": {
        "clean_win": 0.24,
        "win_with_cost": 0.41,
        "disaster": 0.35
      },
      "3": {
        "clean_win": 0.18,
        "win_with_cost": 0.34,
        "disaster": 0.48
      },
      "4": {
        "clean_win": 0.12,
        "win_with_cost": 0.27,
        "disaster": 0.61
      },
      "5": {
        "clean_win": 0.06,
        "win_with_cost": 0.2,
        "disaster": 0.74
      }
    }
  },
  "cases": [
    {
      "id": "elder-anchor",
      "name": "Elder Marisol del Castillo, the Gilded Anchor",
      "kind": "vampire (elder)",
      "turf": "Paradise marina, yacht club, gala circuit",
      "region": "r01",
      "danger": 5,
      "veil_start": 1,
      "mundane_cover": "Old money and philanthropy; the del Castillo name on colonial land grants two centuries older than the marina.",
      "truth": "Camarilla-flavored elder running the Anchor court. Feeds off a VIP cruise-disembark roster delivered 72 hours early by CiDance — she does not hunt, hunting is what poor predators do.",
      "weaknesses": [
        "Sunlight and fire — after two centuries she has made both expensive to deliver",
        "Her supply chain is the lever: disrupt the 72-hour CiDance roster and the court starves politely and visibly",
        "Elysium — she cannot break the gala truce herself; it is armor she cannot take off"
      ],
      "gear_tags": [
        "uv",
        "stake",
        "blessed",
        "fire"
      ],
      "plan": "Do not bring a kit to Marisol del Castillo; bring a calendar. Document the gala circuit, intercept the roster handoff, and let the court starve on schedule.",
      "tells": [
        {
          "id": "elder-anchor-t1",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "Gala photography across decades shows the same unaged face at the Anchor table."
        },
        {
          "id": "elder-anchor-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "The del Castillo land grants predate the marina by two centuries; the family never sold, only 'managed'."
        },
        {
          "id": "elder-anchor-t3",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "She is never seen eating in public — and neither is anyone seated at her table."
        },
        {
          "id": "elder-anchor-t4",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Catering staff describe a table that orders and never eats, tipped too well to remember clearly."
        },
        {
          "id": "elder-anchor-t5",
          "by": [
            "scene",
            "surveillance"
          ],
          "delta": 2,
          "desc": "The slips with the best security cameras hold a feeding roster, not a berth list."
        }
      ],
      "reveal_order": [
        "elder-anchor-t5",
        "elder-anchor-t4",
        "elder-anchor-t2",
        "elder-anchor-t3",
        "elder-anchor-t1"
      ],
      "kit": [
        "uv_rig",
        "stakes",
        "blessed_kit",
        "flares"
      ],
      "kit_total": 165,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.163,
          "table": {
            "clean_win": 0.38,
            "win_with_cost": 0.44,
            "disaster": 0.18
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.922,
          "table": {
            "clean_win": 0.06,
            "win_with_cost": 0.2,
            "disaster": 0.74
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "elder-anchor",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "elder-anchor",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "elder-anchor",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "elder-anchor",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "kingside-tithe",
      "name": "Envoy \"Kingside\", the Crimson Tithe",
      "kind": "vampire",
      "turf": "Jackedsonville Quay, casino back rooms, the loud night",
      "region": "r03",
      "danger": 4,
      "veil_start": 1,
      "mundane_cover": "Nightlife politics — a club-owners' association with a spokesperson; the tax reads as ordinary protection money.",
      "truth": "Anarch-flavored collective that taxes street vice and scavenges festival casualties: the drunk, the alone, the app-mis-paired. Wants the night loud and stable.",
      "weaknesses": [
        "The classics — stake, sun, fire",
        "Consensus-bound: the collective cannot act fast, only deliberately",
        "Needs the night loud — dark the Quay and the Tithe starves, then panics, in that order",
        "Recognition by three off-island princes: humiliate it and bigger fish arrive"
      ],
      "gear_tags": [
        "uv",
        "stake",
        "blessed",
        "fire",
        "armor"
      ],
      "plan": "Map the tribute route from the marginalia, pick a collection night, and make the Quay go quiet at the worst possible hour — let starvation do the loud work.",
      "tells": [
        {
          "id": "kingside-tithe-t1",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "Camera pulls have a gap where a person should be — Kingside does not photograph."
        },
        {
          "id": "kingside-tithe-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "The street tax formalized in 2014, the same year the Crimson Quay rebrand failed — same signatures on both papers."
        },
        {
          "id": "kingside-tithe-t3",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Quay Rojo collectors talk about 'the night owing' in a grammar that predates any gang."
        },
        {
          "id": "kingside-tithe-t4",
          "by": [
            "scene",
            "research"
          ],
          "delta": 2,
          "desc": "The tribute route can be walked from marginalia in returned Book Nook paperbacks — dates, initials, corners."
        },
        {
          "id": "kingside-tithe-t5",
          "by": [
            "surveillance"
          ],
          "delta": 1,
          "desc": "Quay Nights casualties cluster on collection nights."
        }
      ],
      "reveal_order": [
        "kingside-tithe-t5",
        "kingside-tithe-t1",
        "kingside-tithe-t4",
        "kingside-tithe-t3",
        "kingside-tithe-t2"
      ],
      "kit": [
        "uv_rig",
        "stakes",
        "blessed_kit",
        "flares",
        "vest"
      ],
      "kit_total": 465,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.356,
          "table": {
            "clean_win": 0.51,
            "win_with_cost": 0.35,
            "disaster": 0.14
          }
        },
        "rushed": {
          "outcome": "win_with_cost",
          "roll": 0.321,
          "table": {
            "clean_win": 0.12,
            "win_with_cost": 0.27,
            "disaster": 0.61
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "kingside-tithe",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "kingside-tithe",
              "source": "witness",
              "severity": 2,
              "faction": "Coral Trace",
              "note": "a survivor talks; the 48-hour NDA machine wakes up"
            },
            {
              "event": "heat",
              "case": "kingside-tithe",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ]
        }
      }
    },
    {
      "id": "thin-blood-plus-one",
      "name": "\"The Plus-One\" (thin-blood scavenger)",
      "kind": "vampire (thin-blood)",
      "turf": "Migrates the tri-city — Paradise hotel bars, Porto suites, Quay apps",
      "region": "r01-r03",
      "danger": 2,
      "veil_start": 0,
      "mundane_cover": "A date gone wrong: alcohol, a mugging, a tourist who partied too hard. The county has a form for each.",
      "truth": "A thin-blood feeding on app-mis-paired tourists on a two-week orbit through the three cities. Afraid of both courts more than of hunters.",
      "weaknesses": [
        "Thin blood means thin protection — UV and sunlight hurt it properly, a stake works",
        "Addicted to its own app trail — predictable to anyone who plots the geofences",
        "Watched thresholds hold it out (house rule, GM-pending): hotel doors are fine, a watched threshold is not"
      ],
      "gear_tags": [
        "uv",
        "stake",
        "blessed"
      ],
      "plan": "Plot the orbit, be waiting at the after-hours geofence with UV and a watched threshold, and end it quietly before the county's paperwork notices it started.",
      "tells": [
        {
          "id": "thin-blood-plus-one-t1",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Victims remember a wonderful evening and nothing after the second bar — and remember it fondly, which is wrong."
        },
        {
          "id": "thin-blood-plus-one-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "Bite-pattern ER visits recur on a two-week orbit through the three cities."
        },
        {
          "id": "thin-blood-plus-one-t3",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "Victims' phones all end the night inside the same after-hours geofence."
        },
        {
          "id": "thin-blood-plus-one-t4",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Two punctures, healed too fast; a waiter swears the plus-one paid cash for a table of two and ate nothing."
        },
        {
          "id": "thin-blood-plus-one-t5",
          "by": [
            "research"
          ],
          "delta": 1,
          "desc": "No social footprint older than a year — the face is new everywhere it exists."
        }
      ],
      "reveal_order": [
        "thin-blood-plus-one-t2",
        "thin-blood-plus-one-t3",
        "thin-blood-plus-one-t1",
        "thin-blood-plus-one-t5",
        "thin-blood-plus-one-t4"
      ],
      "kit": [
        "uv_rig",
        "stakes",
        "blessed_kit"
      ],
      "kit_total": 140,
      "resolve": {
        "prepared": {
          "outcome": "win_with_cost",
          "roll": 0.807,
          "table": {
            "clean_win": 0.77,
            "win_with_cost": 0.17,
            "disaster": 0.06
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.927,
          "table": {
            "clean_win": 0.24,
            "win_with_cost": 0.41,
            "disaster": 0.35
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "thin-blood-plus-one",
              "source": "witness",
              "severity": 2,
              "faction": "Coral Trace",
              "note": "a survivor talks; the 48-hour NDA machine wakes up"
            },
            {
              "event": "heat",
              "case": "thin-blood-plus-one",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "thin-blood-plus-one",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "thin-blood-plus-one",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "thin-blood-plus-one",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "ghoul-doorman",
      "name": "\"The Doorman\" (Anchor-bound ghoul)",
      "kind": "ghoul",
      "turf": "Paradise marina parking, yacht club service side",
      "region": "r01",
      "danger": 3,
      "veil_start": 1,
      "mundane_cover": "Long-tenured valet captain; marina staff turnover means nobody audits how long 'long' is.",
      "truth": "A ghoul lifer bound to the Anchor court — the wrist-breaker of the border incident. The door is his territory, the court is his god, the flask is his sacrament.",
      "weaknesses": [
        "The blood is the chain — cut the court's supply and the strength curdles into craving within weeks",
        "Disciplined but not patient: provoke, over-answer, regret is his template",
        "He is flesh — restraints and a reason to talk beat a firefight in marina parking"
      ],
      "gear_tags": [
        "melee",
        "armor",
        "blessed"
      ],
      "plan": "Document the flask schedule, interdict one delivery, and be there with restraints when the craving makes him sloppy — then offer him a way to talk that isn't betrayal.",
      "tells": [
        {
          "id": "ghoul-doorman-t1",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Marina staff remember who broke the Tithe collector's wrist, and that both courts called it nothing."
        },
        {
          "id": "ghoul-doorman-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "Staff photos across thirty years show the same man at the same door, unaged, always third from the left."
        },
        {
          "id": "ghoul-doorman-t3",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "He lifts things one-handed that valet captains do not lift one-handed."
        },
        {
          "id": "ghoul-doorman-t4",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "He drinks from a flask on shift that is not liquor, and he never, ever eats."
        }
      ],
      "reveal_order": [
        "ghoul-doorman-t4",
        "ghoul-doorman-t2",
        "ghoul-doorman-t3",
        "ghoul-doorman-t1"
      ],
      "kit": [
        "blessed_kit",
        "machete",
        "vest"
      ],
      "kit_total": 370,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.14,
          "table": {
            "clean_win": 0.64,
            "win_with_cost": 0.26,
            "disaster": 0.1
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.816,
          "table": {
            "clean_win": 0.18,
            "win_with_cost": 0.34,
            "disaster": 0.48
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "ghoul-doorman",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "ghoul-doorman",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "ghoul-doorman",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "ghoul-doorman",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "float-barn-pack",
      "name": "The Float Barn pack (feral ghouls)",
      "kind": "ghoul (feral pack)",
      "turf": "Porto Lujara — float barns and dockside cold storage behind the Carnaval Route",
      "region": "r02",
      "danger": 3,
      "veil_start": 0,
      "mundane_cover": "Dog packs and dock accidents; the CRT's standing 'stray pack' line earns its keep every unload night.",
      "truth": "A leaderless ghoul kennel denning where the crates are warm, eating what unload nights provide, keeping — barely — to a dead domitor's schedule.",
      "weaknesses": [
        "Leaderless: oscillates between frenzy and starvation without a domitor",
        "Fire and daylight both work",
        "Flesh — honest stopping power applies; this is the one entry where the shotgun is the correct answer",
        "Adoptable by a new domitor — a GM door, not a prep plan"
      ],
      "gear_tags": [
        "firearm",
        "fire",
        "melee",
        "armor"
      ],
      "plan": "Pick a non-unload night, bring fire and honest stopping power, clear the barn from the doors inward, and do not open the sealed float until the pack is down.",
      "tells": [
        {
          "id": "float-barn-pack-t1",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "Mauling reports cluster on unload nights, and only on unload nights."
        },
        {
          "id": "float-barn-pack-t2",
          "by": [
            "research",
            "interview"
          ],
          "delta": 2,
          "desc": "Crate counts don't match manifests, and the people who notice get paid to stop noticing."
        },
        {
          "id": "float-barn-pack-t3",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "A generator hums on a shrink-wrapped float that should have run dry."
        },
        {
          "id": "float-barn-pack-t4",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Blood under the diesel smell; scratch marks on the inside of the barn doors."
        },
        {
          "id": "float-barn-pack-t5",
          "by": [
            "interview"
          ],
          "delta": 1,
          "desc": "The barn crew's senior man feeds something on Thursdays and calls it 'the insurance'."
        }
      ],
      "reveal_order": [
        "float-barn-pack-t1",
        "float-barn-pack-t5",
        "float-barn-pack-t4",
        "float-barn-pack-t2",
        "float-barn-pack-t3"
      ],
      "kit": [
        "flares",
        "machete",
        "shotgun",
        "vest"
      ],
      "kit_total": 705,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.622,
          "table": {
            "clean_win": 0.64,
            "win_with_cost": 0.26,
            "disaster": 0.1
          }
        },
        "rushed": {
          "outcome": "clean_win",
          "roll": 0.115,
          "table": {
            "clean_win": 0.18,
            "win_with_cost": 0.34,
            "disaster": 0.48
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "float-barn-pack",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "float-barn-pack",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ]
        }
      }
    },
    {
      "id": "drowned-bellhop",
      "name": "The Drowned Bellhop",
      "kind": "ghost",
      "turf": "CiDance Paradise flagship, floor 14 and the service shaft",
      "region": "r01",
      "danger": 2,
      "veil_start": 0,
      "mundane_cover": "Elevator maintenance and plumbing condensation; guest complaints get comped suites.",
      "truth": "A bellhop who saw a cleanup from the wrong side of a door on floor 14 and 'fell' down the service shaft. He re-enacts his last ninety seconds on cleanup nights.",
      "weaknesses": [
        "Anchor ghost — the sealed accident report and the bright name-tag in lost-and-found are the tethers",
        "Salt slows him at thresholds; cold iron holds a door",
        "He wants the report public more than he wants anyone hurt — expose the file and he goes quiet"
      ],
      "gear_tags": [
        "salt",
        "cold_iron",
        "blessed"
      ],
      "plan": "Salt the corridor, pull the sealed accident report via the Ash List, and publish — the laying is a byline, not a fight.",
      "tells": [
        {
          "id": "drowned-bellhop-t1",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "The service elevator stops on 14 with no call registered, mostly on cleanup nights."
        },
        {
          "id": "drowned-bellhop-t2",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Guests report wet footprints that end at a wall; staff who mention the shaft get rotated off the floor."
        },
        {
          "id": "drowned-bellhop-t3",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "A bellhop 'fell' down that shaft three years ago; Coral Trace sealed the report inside 48 hours."
        },
        {
          "id": "drowned-bellhop-t4",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "A permanent cold spot at the shaft door; the floor's brass name-tags tarnish overnight — except one in lost-and-found that stays bright."
        }
      ],
      "reveal_order": [
        "drowned-bellhop-t4",
        "drowned-bellhop-t1",
        "drowned-bellhop-t3",
        "drowned-bellhop-t2"
      ],
      "kit": [
        "rock_salt",
        "cold_iron",
        "blessed_kit"
      ],
      "kit_total": 175,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.168,
          "table": {
            "clean_win": 0.77,
            "win_with_cost": 0.17,
            "disaster": 0.06
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.907,
          "table": {
            "clean_win": 0.24,
            "win_with_cost": 0.41,
            "disaster": 0.35
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "drowned-bellhop",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "drowned-bellhop",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "drowned-bellhop",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "drowned-bellhop",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "carnaval-drowned",
      "name": "The Carnaval Drowned",
      "kind": "ghost (collective)",
      "turf": "Porto Lujara waterfront, the harbor mouth along the parade route",
      "region": "r02",
      "danger": 2,
      "veil_start": 1,
      "mundane_cover": "Riptide statistics, published annually with the same chart.",
      "truth": "The bill for the week of sanctioned looking-away: party-cruise dead who attend the parade from the wrong side of the railing. Some hands push down. More push up.",
      "weaknesses": [
        "Bound to the route and the week — they only hold strength during Carnaval",
        "Cold iron from the docks — a mooring hook, a fire iron — has authority by provenance",
        "Blessed water cast from the route itself displaces them for the year",
        "The permanent laying is naming the dead publicly, one name at a time"
      ],
      "gear_tags": [
        "cold_iron",
        "blessed",
        "salt"
      ],
      "plan": "Work off-season: pull the harbor master's log, name the dead in print before the route, and keep dock-iron on the railing during the parade itself.",
      "tells": [
        {
          "id": "carnaval-drowned-t1",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "Party-cruise drownings cluster on the same spring tide, same hour, back a decade."
        },
        {
          "id": "carnaval-drowned-t2",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Brass-band veterans drop tempo at the same corner every year without agreeing to."
        },
        {
          "id": "carnaval-drowned-t3",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "Cruise photos from the route show salt-wet figures on the seaward railing who boarded as nobody."
        },
        {
          "id": "carnaval-drowned-t4",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "During Carnaval the route's water runs ten degrees colder than the bay and smells of perfume, not diesel."
        }
      ],
      "reveal_order": [
        "carnaval-drowned-t2",
        "carnaval-drowned-t1",
        "carnaval-drowned-t3",
        "carnaval-drowned-t4"
      ],
      "kit": [
        "rock_salt",
        "cold_iron",
        "blessed_kit"
      ],
      "kit_total": 175,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.446,
          "table": {
            "clean_win": 0.77,
            "win_with_cost": 0.17,
            "disaster": 0.06
          }
        },
        "rushed": {
          "outcome": "win_with_cost",
          "roll": 0.282,
          "table": {
            "clean_win": 0.24,
            "win_with_cost": 0.41,
            "disaster": 0.35
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "carnaval-drowned",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "carnaval-drowned",
              "source": "witness",
              "severity": 2,
              "faction": "Coral Trace",
              "note": "a survivor talks; the 48-hour NDA machine wakes up"
            },
            {
              "event": "heat",
              "case": "carnaval-drowned",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ]
        }
      }
    },
    {
      "id": "wrong-door",
      "name": "The Wrong-Door",
      "kind": "ghost",
      "turf": "Jackedsonville tenement next to a licensed club, one sealed apartment",
      "region": "r03",
      "danger": 1,
      "veil_start": 0,
      "mundane_cover": "A gas-leak evacuation that never quite ends; the building stays half-empty 'pending inspection'.",
      "truth": "A raid victim correcting the record one knock at a time, forever. Not bound by thresholds — bound by paperwork. Danger 1 to hunters, 4 to the officers involved.",
      "weaknesses": [
        "Salt does nothing — he is bound by records, not thresholds",
        "The correction is the tether: amend the incident report to the truth — the real address, the real name — and he stops knocking",
        "He cannot be fought, only refused or answered; force makes you his new subject"
      ],
      "gear_tags": [
        "blessed"
      ],
      "plan": "No loadout — bring a folder. Get the raid's incident report amended to the true address and the true name, and say the name in the apartment.",
      "tells": [
        {
          "id": "wrong-door-t1",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "A CRT Tier-3 hit the wrong door on this block; the incident report's address was corrected after filing."
        },
        {
          "id": "wrong-door-t2",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "Body-cam footage from the raid glitches at one apartment number — always the same one."
        },
        {
          "id": "wrong-door-t3",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Officers request transfer off the beat and won't say why; the balcony patrons who filmed it sold the clip nowhere."
        },
        {
          "id": "wrong-door-t4",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Knocking in threes from inside the sealed unit — the seal tape never broken, the knocking from inside the seal."
        }
      ],
      "reveal_order": [
        "wrong-door-t1",
        "wrong-door-t3",
        "wrong-door-t2",
        "wrong-door-t4"
      ],
      "kit": [
        "blessed_kit"
      ],
      "kit_total": 40,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.647,
          "table": {
            "clean_win": 0.9,
            "win_with_cost": 0.08,
            "disaster": 0.02
          }
        },
        "rushed": {
          "outcome": "clean_win",
          "roll": 0.192,
          "table": {
            "clean_win": 0.3,
            "win_with_cost": 0.48,
            "disaster": 0.22
          }
        },
        "heat": {
          "prepared": [],
          "rushed": []
        }
      }
    },
    {
      "id": "object-14",
      "name": "Object 14",
      "kind": "cursed object (class unknown)",
      "turf": "InterFederal Shores reef station 7 → tri-city gray market",
      "region": "r14",
      "danger": 3,
      "veil_start": 2,
      "mundane_cover": "An Ash List meme. Half the moderation queue is 'Object 14' traffic; the serious editors burn out on schedule.",
      "truth": "A waterproof field notebook in a humidity-proof bag, pages rewriting into tide tables for coasts that don't exist. Possession dries you out — you stop sweating, then crying, then start numbering things. The Dry Contract's calling card.",
      "weaknesses": [
        "An object, not an entity — it does not fight; the contract behind it does",
        "Resists fire unless the fire is fed with salt",
        "The clean lay is return: 120 meters down, on the blip, pages left open — do not read it on the way down",
        "Never bring it east of the bay"
      ],
      "gear_tags": [
        "salt",
        "blessed",
        "fire"
      ],
      "plan": "Track the gray-market chain, contain it in salt and blessed cord, and either burn it salt-fed on a dry dock at dawn or charter the drop to 120 meters.",
      "tells": [
        {
          "id": "object-14-t1",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "Reef station 7's log numbering restarts at 14 every page; the archivist noticed, then stopped noticing."
        },
        {
          "id": "object-14-t2",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Paper curls and salt-lines crumble near the bag — the damp inside never dries."
        },
        {
          "id": "object-14-t3",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "The pawn broker who held it describes the week he stopped dreaming about water."
        },
        {
          "id": "object-14-t4",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "It has surfaced twice: a Ledger Row pawn shop priced as 'surplus', and the estate sale of a coast-guard officer whose family never opened the bag."
        },
        {
          "id": "object-14-t5",
          "by": [
            "surveillance"
          ],
          "delta": 1,
          "desc": "Ash List 'Object 14' meme spikes trace back to one coast-guard posting cycle."
        }
      ],
      "reveal_order": [
        "object-14-t3",
        "object-14-t1",
        "object-14-t5",
        "object-14-t2",
        "object-14-t4"
      ],
      "kit": [
        "rock_salt",
        "blessed_kit",
        "flares"
      ],
      "kit_total": 80,
      "resolve": {
        "prepared": {
          "outcome": "win_with_cost",
          "roll": 0.796,
          "table": {
            "clean_win": 0.64,
            "win_with_cost": 0.26,
            "disaster": 0.1
          }
        },
        "rushed": {
          "outcome": "win_with_cost",
          "roll": 0.261,
          "table": {
            "clean_win": 0.18,
            "win_with_cost": 0.34,
            "disaster": 0.48
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "object-14",
              "source": "witness",
              "severity": 2,
              "faction": "Coral Trace",
              "note": "a survivor talks; the 48-hour NDA machine wakes up"
            },
            {
              "event": "heat",
              "case": "object-14",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "object-14",
              "source": "witness",
              "severity": 2,
              "faction": "Coral Trace",
              "note": "a survivor talks; the 48-hour NDA machine wakes up"
            },
            {
              "event": "heat",
              "case": "object-14",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ]
        }
      }
    },
    {
      "id": "harvest-crown",
      "name": "The Harvest Crown",
      "kind": "cursed object",
      "turf": "Villa Miel festival-committee storage; worn publicly one night a year",
      "region": "r04",
      "danger": 4,
      "veil_start": 1,
      "mundane_cover": "Festival tradition — re-woven annually, town pride, a parade accessory.",
      "truth": "The hive's antenna. The rite funnels the festival's appetite through the queen, and the queen hears the hive for a night. Sixty years of 're-woven annually' and it has never once looked new.",
      "weaknesses": [
        "Off-season it is nearly inert — the window matters more than the weapon",
        "Unweave it strand by strand while naming every queen who wore it — the committee's minutes have the names",
        "Burn it before the harvest moon; after the moon it regrows with the cane",
        "Smoke befuddles its connection"
      ],
      "gear_tags": [
        "blessed",
        "smoke",
        "salt"
      ],
      "plan": "Move off-season with blessed cutters and the minutes' queen list; unweave in a salted room with a smoker going, and be off the island before the committee counts strands.",
      "tells": [
        {
          "id": "harvest-crown-t1",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "The committee minutes carry the same crowning paragraph verbatim, sixty years deep."
        },
        {
          "id": "harvest-crown-t2",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Cane flowers out of season in a spiral centered on the storage barn."
        },
        {
          "id": "harvest-crown-t3",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "A retired festival queen will describe the shared dream — for good coffee and no recording."
        },
        {
          "id": "harvest-crown-t4",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "It surfaced once mislabeled as folk art in a Ruby Harbor estate sale; the buyer mailed it back within the week, no note."
        },
        {
          "id": "harvest-crown-t5",
          "by": [
            "surveillance"
          ],
          "delta": 1,
          "desc": "Committee storage keeps a climate bill the cane doesn't need — something in there is kept cool and moist on purpose."
        }
      ],
      "reveal_order": [
        "harvest-crown-t1",
        "harvest-crown-t5",
        "harvest-crown-t3",
        "harvest-crown-t2",
        "harvest-crown-t4"
      ],
      "kit": [
        "rock_salt",
        "blessed_kit",
        "bee_smoker"
      ],
      "kit_total": 90,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.325,
          "table": {
            "clean_win": 0.51,
            "win_with_cost": 0.35,
            "disaster": 0.14
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.899,
          "table": {
            "clean_win": 0.12,
            "win_with_cost": 0.27,
            "disaster": 0.61
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "harvest-crown",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "harvest-crown",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "harvest-crown",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "harvest-crown",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "mirror-compact",
      "name": "The Mirror Compact",
      "kind": "cursed object (fae spill)",
      "turf": "Drifted — estate sales, pawn shops, hotel lost-and-found",
      "region": "r10",
      "danger": 2,
      "veil_start": 1,
      "mundane_cover": "Vintage vanity; the most lost-and-found object imaginable.",
      "truth": "A dancer's compact from a Lagooni Seika dressing room — glamour on loan. Each use makes you more of what the room wants, and a little of the real face stays in the glass. Old ones have crowded glass.",
      "weaknesses": [
        "Cold iron to the glass shows the crowd inside and breaks the active glamour",
        "Salt across the lid seals it for transport",
        "Shatter it in front of its owner while they look at their true reflection — the faces go home",
        "Do not look in it to check"
      ],
      "gear_tags": [
        "cold_iron",
        "salt"
      ],
      "plan": "Trace the lost-and-found chain, seal it salted in a cold-iron-lined box, and bring the owner to a true mirror before the glass gets more crowded.",
      "tells": [
        {
          "id": "mirror-compact-t1",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "A performer who 'found her look' overnight now reads her own pre-season photos as a stranger."
        },
        {
          "id": "mirror-compact-t2",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Backstage mirrors are covered during shows, by house rule, no exceptions — and the dressing-room iron is missing."
        },
        {
          "id": "mirror-compact-t3",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "The compact's make went out of production in the fifties; the powder inside is fresh."
        },
        {
          "id": "mirror-compact-t4",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "Its owner is becoming what each room wants — the mannerisms change per venue like a delayed broadcast."
        }
      ],
      "reveal_order": [
        "mirror-compact-t4",
        "mirror-compact-t1",
        "mirror-compact-t3",
        "mirror-compact-t2"
      ],
      "kit": [
        "rock_salt",
        "cold_iron"
      ],
      "kit_total": 135,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.114,
          "table": {
            "clean_win": 0.77,
            "win_with_cost": 0.17,
            "disaster": 0.06
          }
        },
        "rushed": {
          "outcome": "clean_win",
          "roll": 0.073,
          "table": {
            "clean_win": 0.24,
            "win_with_cost": 0.41,
            "disaster": 0.35
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "mirror-compact",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "mirror-compact",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ]
        }
      }
    },
    {
      "id": "ridge-runner",
      "name": "The Black Sand ridge-runner",
      "kind": "werewolf (Garou)",
      "turf": "Black Sand Beach Preserve, north-tip trails and survey lines",
      "region": "r11",
      "danger": 5,
      "veil_start": 1,
      "mundane_cover": "Feral dogs and turtle-poacher scares, backed by the eco-NGO's own safety briefings — the pack files its own cover with the county.",
      "truth": "A Garou patrolling its charge. The preserve is its post, the turtles are its neighbors, and the Wyrm-tainted condo money moving through the Development Consortium is its war.",
      "weaknesses": [
        "Silver is real, and so is the wolfsbane analog — you could win the first exchange",
        "The pack's response to losing a member is not a second exchange",
        "The correct prep is a briefcase: bring proof of the condo money's taint and get an ally, not a fight"
      ],
      "gear_tags": [
        "silver",
        "armor"
      ],
      "plan": "Do not pack silver for the ridge-runner; pack documents. Survey the Consortium's unpublished soil studies, carry proof up the trail in daylight, and let the pack's war do the rest.",
      "tells": [
        {
          "id": "ridge-runner-t1",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Dog tracks that change gait mid-trail; claw marks on survey stakes eight feet up."
        },
        {
          "id": "ridge-runner-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "NGO staff who appear in no census, payroll, or visa file, year over year."
        },
        {
          "id": "ridge-runner-t3",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Condo survey crews quit en masse after night work and pay their own contract penalties without complaint."
        },
        {
          "id": "ridge-runner-t4",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "The preserve's night cameras fail in a moving pattern, not a fixed one."
        }
      ],
      "reveal_order": [
        "ridge-runner-t1",
        "ridge-runner-t3",
        "ridge-runner-t4",
        "ridge-runner-t2"
      ],
      "kit": [
        "silver",
        "vest"
      ],
      "kit_total": 700,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.124,
          "table": {
            "clean_win": 0.38,
            "win_with_cost": 0.44,
            "disaster": 0.18
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.621,
          "table": {
            "clean_win": 0.06,
            "win_with_cost": 0.2,
            "disaster": 0.74
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "ridge-runner",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "ridge-runner",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "ridge-runner",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "ridge-runner",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "mirror-court",
      "name": "The Lagoona Mirror Court",
      "kind": "fae court",
      "turf": "Lagooni Seika boardwalk — burlesque rooms, Sizzle Fest arches, backstage",
      "region": "r10",
      "danger": 3,
      "veil_start": 1,
      "mundane_cover": "Show-business eccentricity — a devoted burlesque season with strange house rules reads as brand, and on the east coast it is brand.",
      "truth": "A fae court harvesting glamour off the boardwalk. Applause is the crop, performers are the orchard; they prune, they graft, they do not ask the trees.",
      "weaknesses": [
        "Cold iron, the oldest clause — it must touch them, which is why melee doctrine exists",
        "Their word binds them literally, to the comma",
        "Applause is the harvest — a silent house starves them faster than any weapon",
        "Salt at thresholds marks a room they cannot glamour"
      ],
      "gear_tags": [
        "cold_iron",
        "salt",
        "blessed"
      ],
      "plan": "Carry dock-iron on your person, salt the dressing-room thresholds, and negotiate nothing verbally — make them write it, then read the commas back.",
      "tells": [
        {
          "id": "mirror-court-t1",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "Sizzle Fest crowds cheer one beat too late, in unison, like a delayed broadcast."
        },
        {
          "id": "mirror-court-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "Performer headshots across seasons trend younger."
        },
        {
          "id": "mirror-court-t3",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Patrons lose an hour between the boardwalk arches and remember it as the best part."
        },
        {
          "id": "mirror-court-t4",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Every backstage mirror is covered during shows by house rule; the dressing-room iron is missing."
        },
        {
          "id": "mirror-court-t5",
          "by": [
            "research"
          ],
          "delta": 1,
          "desc": "The Court's talent poaching reaches into CiDance 'wellness retreat' packages — two poached Sirens turned up beaten and nobody filed anything."
        }
      ],
      "reveal_order": [
        "mirror-court-t4",
        "mirror-court-t3",
        "mirror-court-t1",
        "mirror-court-t2",
        "mirror-court-t5"
      ],
      "kit": [
        "rock_salt",
        "cold_iron",
        "blessed_kit"
      ],
      "kit_total": 175,
      "resolve": {
        "prepared": {
          "outcome": "win_with_cost",
          "roll": 0.673,
          "table": {
            "clean_win": 0.64,
            "win_with_cost": 0.26,
            "disaster": 0.1
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.578,
          "table": {
            "clean_win": 0.18,
            "win_with_cost": 0.34,
            "disaster": 0.48
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "mirror-court",
              "source": "witness",
              "severity": 2,
              "faction": "Coral Trace",
              "note": "a survivor talks; the 48-hour NDA machine wakes up"
            },
            {
              "event": "heat",
              "case": "mirror-court",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "mirror-court",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "mirror-court",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "mirror-court",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "dry-contract",
      "name": "The Dry Contract",
      "kind": "island-unique (contract phenomenon)",
      "turf": "The east side — Lagooni Seika outward toward East Bayby, strongest at the coast",
      "region": "r10",
      "danger": 5,
      "veil_start": 2,
      "mundane_cover": "A rain shadow, a microclimate, and a very good engineering department. The east side simply doesn't flood, and the island is proud of it.",
      "truth": "Not a creature — a contract. Moisture on the east side goes somewhere; in exchange the east side never floods and the water bills never move. Somebody signed for the town. Nobody alive consented and everybody pays.",
      "weaknesses": [
        "You cannot stake a clause — void the terms: return the water (a genuine flood, or a blessed baptism of the signatory site)",
        "Name the signatory — a research endgame the whole cell survives or doesn't",
        "Salt and blessed water in quantity break local enforcement in a small zone for a short time — extraction, not victory",
        "Offering it a better deal is a door the GM owns; the prep doctrine does not recommend it"
      ],
      "gear_tags": [
        "salt",
        "blessed",
        "seawater"
      ],
      "plan": "Build the paper case first — charter, signatory, water bills — then break a small enforcement zone with salt and blessed seawater long enough to extract whoever the contract is billing.",
      "tells": [
        {
          "id": "dry-contract-t1",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "East-side humidity readings sit twenty points below the island model, every month, for years."
        },
        {
          "id": "dry-contract-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "The casino-hotels' water bills are flat for a decade while occupancy doubled."
        },
        {
          "id": "dry-contract-t3",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "A 1970s water-district charter names a signatory the county has no record of."
        },
        {
          "id": "dry-contract-t4",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "East-side residents 'don't dream about water anymore', and say so like it's a joke."
        },
        {
          "id": "dry-contract-t5",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "Salt-lines laid across the enforcement zone crumble to powder overnight — the salt dries from the inside."
        },
        {
          "id": "dry-contract-t6",
          "by": [
            "scene"
          ],
          "delta": 1,
          "desc": "Pools, fountains, and dehumidifiers all run low; maintenance logs call it evaporation in 90% humidity."
        }
      ],
      "reveal_order": [
        "dry-contract-t4",
        "dry-contract-t5",
        "dry-contract-t1",
        "dry-contract-t2",
        "dry-contract-t3",
        "dry-contract-t6"
      ],
      "kit": [
        "rock_salt",
        "blessed_kit",
        "seawater"
      ],
      "kit_total": 55,
      "resolve": {
        "prepared": {
          "outcome": "clean_win",
          "roll": 0.239,
          "table": {
            "clean_win": 0.38,
            "win_with_cost": 0.44,
            "disaster": 0.18
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.403,
          "table": {
            "clean_win": 0.06,
            "win_with_cost": 0.2,
            "disaster": 0.74
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "dry-contract",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "dry-contract",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "dry-contract",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "dry-contract",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    },
    {
      "id": "hive-cane",
      "name": "The Hive under the cane (Honeycomb Choir focus)",
      "kind": "island-unique (hive)",
      "turf": "Villa Miel — cane country inland of the festival town; distribution runs island-wide",
      "region": "r04",
      "danger": 4,
      "veil_start": 1,
      "mundane_cover": "Festival tradition and the apiary industry. Town pride with a parade.",
      "truth": "Not a goddess — a hive. The Choir is the beekeeping apparatus: the committee tends it, the Miel Boys distribute its product without asking, the gratitude circles recruit its middle managers, and the festival feeds it a town's worth of wanting one night a year.",
      "weaknesses": [
        "Bee-logic: smoke calms and confuses its attention",
        "Cold — at the harvest moon it is enormous; off-season it is sluggish and nearly deaf",
        "The Harvest Crown is its antenna — unweave the crown off-season and the rite goes dark for a year",
        "It cannot cross running seawater — cane country is inland for a reason; a retreat to the coast is a real retreat"
      ],
      "gear_tags": [
        "smoke",
        "blessed",
        "seawater",
        "salt"
      ],
      "plan": "Work off-season with smokers and blessed kit, unweave the crown first, and keep a running-seawater line between you and the cane while the committee is evacuated, not martyred.",
      "tells": [
        {
          "id": "hive-cane-t1",
          "by": [
            "research",
            "scene"
          ],
          "delta": 2,
          "desc": "Honey barrel sugar content is wrong — and the wrong barrels move through IFC cold-chain manifests that otherwise check out."
        },
        {
          "id": "hive-cane-t2",
          "by": [
            "research"
          ],
          "delta": 2,
          "desc": "The festival committee's minutes carry one verbatim paragraph, sixty years deep."
        },
        {
          "id": "hive-cane-t3",
          "by": [
            "interview"
          ],
          "delta": 2,
          "desc": "Festival queens share a dream before crowning — and Paradise gratitude-circle converts describe the same dream, four cities away."
        },
        {
          "id": "hive-cane-t4",
          "by": [
            "surveillance"
          ],
          "delta": 2,
          "desc": "Cane flowers out of season in a spiral centered on the storage barn — visible from any small aircraft."
        },
        {
          "id": "hive-cane-t5",
          "by": [
            "scene"
          ],
          "delta": 2,
          "desc": "The honey smells of the boardwalk, the gala, and the parade — it is flavored by appetite, and a good nose can read last year's festival in it."
        }
      ],
      "reveal_order": [
        "hive-cane-t5",
        "hive-cane-t3",
        "hive-cane-t4",
        "hive-cane-t1",
        "hive-cane-t2"
      ],
      "kit": [
        "rock_salt",
        "blessed_kit",
        "bee_smoker",
        "seawater"
      ],
      "kit_total": 90,
      "resolve": {
        "prepared": {
          "outcome": "win_with_cost",
          "roll": 0.776,
          "table": {
            "clean_win": 0.51,
            "win_with_cost": 0.35,
            "disaster": 0.14
          }
        },
        "rushed": {
          "outcome": "disaster",
          "roll": 0.702,
          "table": {
            "clean_win": 0.12,
            "win_with_cost": 0.27,
            "disaster": 0.61
          }
        },
        "heat": {
          "prepared": [
            {
              "event": "heat",
              "case": "hive-cane",
              "source": "witness",
              "severity": 2,
              "faction": "Coral Trace",
              "note": "a survivor talks; the 48-hour NDA machine wakes up"
            },
            {
              "event": "heat",
              "case": "hive-cane",
              "source": "cleanup_bill",
              "severity": 1,
              "faction": "Stevens",
              "note": "a sanitation line item with the case's address in the description field"
            }
          ],
          "rushed": [
            {
              "event": "heat",
              "case": "hive-cane",
              "source": "gunfire",
              "severity": 2,
              "faction": "CRT",
              "note": "shots logged in a licensed zone — a sergeant asks for the optics calendar"
            },
            {
              "event": "heat",
              "case": "hive-cane",
              "source": "collateral",
              "severity": 3,
              "faction": "CRT",
              "note": "bystander/property damage forces a tier review"
            },
            {
              "event": "heat",
              "case": "hive-cane",
              "source": "cleanup_bill",
              "severity": 2,
              "faction": "Stevens",
              "note": "Team 7 re-tasked; the invoice names a hunter"
            }
          ]
        }
      }
    }
  ]
};
