"""
Cursor hooks for mem-constant session carryover.

Invoked as:
  py -3 .cursor/hooks/mem_constant_carryover_hooks.py beforeSubmitPrompt
  py -3 .cursor/hooks/mem_constant_carryover_hooks.py afterAgentResponse
  py -3 .cursor/hooks/mem_constant_carryover_hooks.py sessionEnd

Reads hook JSON from stdin; writes stdout JSON as required per hook type.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

MEM_CONSTANT_YAML = "mem-constant.yaml"
BUFFER_NAME = ".hook-buffer.jsonl"
LAST_SESSION = "last-session.md"
CARRYOVER_DIR = ".mem-constant"
MAX_BUFFER_LINES = 500
MAX_USER_CHARS = 50_000
MAX_ASSIST_CHARS = 200_000
MAX_TRANSCRIPT_CHARS = 100_000


def _out(obj: dict) -> int:
    sys.stdout.write(json.dumps(obj))
    return 0


def _find_project_root(start: Path) -> Path | None:
    cur = start.resolve()
    if cur.is_file():
        cur = cur.parent
    for p in [cur, *cur.parents]:
        if (p / MEM_CONSTANT_YAML).is_file():
            return p
    return None


def _workspace_roots(data: dict) -> list[Path]:
    roots = data.get("workspace_roots") or []
    return [Path(r) for r in roots if r]


def _carryover_dir(root: Path) -> Path:
    return root / CARRYOVER_DIR


def _buffer_path(root: Path) -> Path:
    return _carryover_dir(root) / BUFFER_NAME


def _last_session_path(root: Path) -> Path:
    return _carryover_dir(root) / LAST_SESSION


def _clip(s: str, n: int) -> str:
    if len(s) <= n:
        return s
    return s[: n - 24] + "\n\n… [truncated] …\n"


def _append_buffer(root: Path, role: str, text: str) -> None:
    d = _carryover_dir(root)
    d.mkdir(parents=True, exist_ok=True)
    p = _buffer_path(root)
    if role == "user":
        text = _clip(text, MAX_USER_CHARS)
    elif role == "assistant":
        text = _clip(text, MAX_ASSIST_CHARS)
    line = json.dumps(
        {"role": role, "text": text, "ts": datetime.now(timezone.utc).isoformat()},
        ensure_ascii=False,
    )
    lines: list[str] = []
    if p.is_file():
        lines = p.read_text(encoding="utf-8", errors="replace").splitlines()
    lines.append(line)
    lines = lines[-MAX_BUFFER_LINES:]
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _buffer_to_markdown(root: Path) -> str:
    p = _buffer_path(root)
    if not p.is_file():
        return ""
    chunks: list[str] = []
    for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            o = json.loads(line)
        except json.JSONDecodeError:
            continue
        role = o.get("role", "?")
        text = o.get("text", "")
        chunks.append(f"### {role}\n\n{text}\n")
    if not chunks:
        return ""
    return "## Recent messages (hook buffer)\n\n" + "\n".join(chunks)


def _transcript_to_markdown(path: Path) -> str:
    if not path.is_file():
        return ""
    raw = path.read_text(encoding="utf-8", errors="replace")
    if not raw.strip():
        return ""
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return "## Transcript (raw excerpt)\n\n```\n" + _clip(raw, MAX_TRANSCRIPT_CHARS) + "\n```\n"

    msgs: list | None = None
    if isinstance(data, list):
        msgs = data
    elif isinstance(data, dict):
        for k in ("messages", "conversation", "turns", "history", "chat"):
            v = data.get(k)
            if isinstance(v, list):
                msgs = v
                break
    if not msgs:
        return "## Transcript (JSON excerpt)\n\n```json\n" + _clip(raw, MAX_TRANSCRIPT_CHARS) + "\n```\n"

    parts = ["## Transcript (parsed tail)\n"]
    for m in msgs[-48:]:
        if not isinstance(m, dict):
            continue
        role = m.get("role") or m.get("type") or "unknown"
        content = m.get("content") or m.get("text") or m.get("message") or ""
        if isinstance(content, list):
            content = json.dumps(content, ensure_ascii=False)
        parts.append(f"### {role}\n\n{str(content)}\n")
    return "\n".join(parts)


def _clear_buffer(root: Path) -> None:
    p = _buffer_path(root)
    if p.is_file():
        p.unlink()


def run_session_end(data: dict) -> int:
    roots = _workspace_roots(data)
    if not roots:
        return _out({})

    root = _find_project_root(roots[0])
    if not root:
        return _out({})

    reason = data.get("reason", "")
    session_id = data.get("session_id", data.get("conversation_id", ""))
    tp = data.get("transcript_path")
    tp_path = Path(tp) if tp else None

    buf_md = _buffer_to_markdown(root)
    tr_md = ""
    if tp_path:
        tr_md = _transcript_to_markdown(tp_path)

    header = f"""# Auto carryover

_Generated by mem-constant Cursor hooks when the composer session ended._

- **When (UTC):** {datetime.now(timezone.utc).isoformat()}
- **Session:** `{session_id}`
- **Reason:** `{reason}`
- **Hook:** `{data.get("hook_event_name", "")}`

"""
    if not tr_md and not buf_md:
        body = (
            "_No transcript path and no buffered messages._\n\n"
            "Enable **chat/composer transcripts** in Cursor if available, or rely on "
            "`beforeSubmitPrompt` / `afterAgentResponse` hooks (should populate the buffer during the session).\n"
        )
    else:
        body = (tr_md + "\n\n" if tr_md else "") + (buf_md if buf_md else "")

    out_path = _last_session_path(root)
    _carryover_dir(root).mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + body, encoding="utf-8")
    _clear_buffer(root)
    return _out({})


def run_before_submit_prompt(data: dict) -> int:
    roots = _workspace_roots(data)
    if not roots:
        return _out({"continue": True})
    root = _find_project_root(roots[0])
    if not root:
        return _out({"continue": True})
    prompt = data.get("prompt") or ""
    if prompt.strip():
        try:
            _append_buffer(root, "user", prompt)
        except OSError:
            pass
    return _out({"continue": True})


def run_after_agent_response(data: dict) -> int:
    roots = _workspace_roots(data)
    if not roots:
        return _out({})
    root = _find_project_root(roots[0])
    if not root:
        return _out({})
    text = data.get("text") or ""
    if text.strip():
        try:
            _append_buffer(root, "assistant", text)
        except OSError:
            pass
    return _out({})


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    raw = sys.stdin.read()
    if not raw.strip():
        if mode == "beforeSubmitPrompt":
            return _out({"continue": True})
        return _out({})
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        if mode == "beforeSubmitPrompt":
            return _out({"continue": True})
        return _out({})

    if mode == "beforeSubmitPrompt":
        return run_before_submit_prompt(data)
    if mode == "afterAgentResponse":
        return run_after_agent_response(data)
    if mode == "sessionEnd":
        return run_session_end(data)
    return _out({})


if __name__ == "__main__":
    raise SystemExit(main())
